# Seed regions
# Region.delete_all
# Region.create!(name: "North Africa") #id 1
# Region.create!(name: "Sub-Saharan Africa") #id 2
# Region.create!(name: "East Asia") #id 3
# Region.create!(name: "North Asia") #id 4
# Region.create!(name: "West & Central Asia") #id 5
# Region.create!(name: "South & Southeast Asia") #id 6
# Region.create!(name: "Oceania") #id 7
# Region.create!(name: "Europe") #id 8
# Region.create!(name: "North America") #id 9
# Region.create!(name: "Central America") #id 10
# Region.create!(name: "Caribbean Islands") #id 11
# Region.create!(name: "South America") #id 12


# #Seed countries

# Country.delete_all
# Country.create!(iso: "AD", name: "Andorra", region_id: 8)
# Country.create!(iso: "AE", name: "United Arab Emirates", region_id: 5)
# Country.create!(iso: "AF", name: "Afghanistan", region_id: 5)
# Country.create!(iso: "AG", name: "Antigua and Barbuda", region_id: 11)
# Country.create!(iso: "AL", name: "Albania", region_id: 8)
# Country.create!(iso: "AM", name: "Armenia", region_id: 5)
# Country.create!(iso: "AO", name: "Angola", region_id: 2)
# Country.create!(iso: "AR", name: "Argentina", region_id: 12)
# Country.create!(iso: "AT", name: "Austria", region_id: 8)
# Country.create!(iso: "AU", name: "Australia", region_id: 7)
# Country.create!(iso: "AZ", name: "Azerbaijan", region_id: 5)
# Country.create!(iso: "BA", name: "Bosnia and Herzegovina", region_id: 8)
# Country.create!(iso: "BB", name: "Barbados", region_id: 11)
# Country.create!(iso: "BD", name: "Bangladesh", region_id: 6)
# Country.create!(iso: "BE", name: "Belgium", region_id: 8)
# Country.create!(iso: "BF", name: "Burkina Faso", region_id: 2)
# Country.create!(iso: "BG", name: "Bulgaria", region_id: 8)
# Country.create!(iso: "BH", name: "Bahrain", region_id: 5)
# Country.create!(iso: "BI", name: "Burundi", region_id: 2)
# Country.create!(iso: "BJ", name: "Benin", region_id: 2)
# Country.create!(iso: "BM", name: "Bermuda", region_id: 11)
# Country.create!(iso: "BN", name: "Brunei", region_id: 6)
# Country.create!(iso: "BO", name: "Bolivia", region_id: 12)
# Country.create!(iso: "BR", name: "Brazil", region_id: 12)
# Country.create!(iso: "BS", name: "Bahamas", region_id: 11)
# Country.create!(iso: "BT", name: "Bhutan", region_id: 6)
# Country.create!(iso: "BW", name: "Botswana", region_id: 2)
# Country.create!(iso: "BY", name: "Belarus", region_id: 4)
# Country.create!(iso: "BZ", name: "Belize", region_id: 10)
# Country.create!(iso: "CA", name: "Canada", region_id: 9)
# Country.create!(iso: "CD", name: "Democratic Republic of the Congo", region_id: 2)
# Country.create!(iso: "CF", name: "Central African Republic", region_id: 2)
# Country.create!(iso: "CG", name: "Republic of the Congo", region_id: 2)
# Country.create!(iso: "CH", name: "Switzerland", region_id: 8)
# Country.create!(iso: "CI", name: "Cote d'Ivoire", region_id: 2)
# Country.create!(iso: "CL", name: "Chile", region_id: 12)
# Country.create!(iso: "CM", name: "Cameroon", region_id: 2)
# Country.create!(iso: "CN", name: "China", region_id: 3)
# Country.create!(iso: "CO", name: "Colombia", region_id: 12)
# Country.create!(iso: "CR", name: "Costa Rica", region_id: 10)
# Country.create!(iso: "CU", name: "Cuba", region_id: 11)
# Country.create!(iso: "CV", name: "Cape Verde", region_id: 2)
# Country.create!(iso: "CY", name: "Cyprus", region_id: 5)
# Country.create!(iso: "CZ", name: "Czech Republic", region_id: 8)
# Country.create!(iso: "DE", name: "Germany", region_id: 8)
# Country.create!(iso: "DJ", name: "Djibouti", region_id: 2)
# Country.create!(iso: "DK", name: "Denmark", region_id: 8)
# Country.create!(iso: "DM", name: "Dominica", region_id: 11)
# Country.create!(iso: "DO", name: "Dominican Republic", region_id: 11)
# Country.create!(iso: "DZ", name: "Algeria", region_id: 1)
# Country.create!(iso: "EC", name: "Ecuador", region_id: 12)
# Country.create!(iso: "EE", name: "Estonia", region_id: 8)
# Country.create!(iso: "EG", name: "Egypt", region_id: 1)
# Country.create!(iso: "EH", name: "Western Sahara", region_id: 1)
# Country.create!(iso: "ER", name: "Eritrea", region_id: 2)
# Country.create!(iso: "ES", name: "Spain", region_id: 8)
# Country.create!(iso: "ET", name: "Ethiopia", region_id: 2)
# Country.create!(iso: "FI", name: "Finland", region_id: 8)
# Country.create!(iso: "FJ", name: "Fiji", region_id: 7)
# Country.create!(iso: "FM", name: "Micronesia", region_id: 7)
# Country.create!(iso: "FR", name: "France", region_id: 8)
# Country.create!(iso: "GA", name: "Gabon", region_id: 2)
# Country.create!(iso: "GB", name: "United Kingdom", region_id: 8)
# Country.create!(iso: "GD", name: "Grenada", region_id: 11)
# Country.create!(iso: "GE", name: "Georgia", region_id: 5)
# Country.create!(iso: "GH", name: "Ghana", region_id: 2)
# Country.create!(iso: "GL", name: "Greenland", region_id: 8)
# Country.create!(iso: "GM", name: "Gambia", region_id: 2)
# Country.create!(iso: "GN", name: "Guinea", region_id: 2)
# Country.create!(iso: "GQ", name: "Equatorial Guinea", region_id: 2)
# Country.create!(iso: "GR", name: "Greece", region_id: 8)
# Country.create!(iso: "GT", name: "Guatemala", region_id: 10)    
# Country.create!(iso: "GW", name: "Guinea-Bissau", region_id: 2)
# Country.create!(iso: "GY", name: "Guyana", region_id: 12)
# Country.create!(iso: "HK", name: "Hong Kong", region_id: 3)
# Country.create!(iso: "HN", name: "Honduras", region_id: 10)
# Country.create!(iso: "HR", name: "Croatia", region_id: 8)
# Country.create!(iso: "HT", name: "Haiti", region_id: 11)
# Country.create!(iso: "HU", name: "Hungary", region_id: 8)
# Country.create!(iso: "ID", name: "Indonesia", region_id: 6)
# Country.create!(iso: "IE", name: "Ireland", region_id: 8)
# Country.create!(iso: "IL", name: "Israel", region_id: 5)
# Country.create!(iso: "IN", name: "India", region_id: 6)
# Country.create!(iso: "IQ", name: "Iraq", region_id: 5)
# Country.create!(iso: "IR", name: "Iran", region_id: 5)
# Country.create!(iso: "IS", name: "Iceland", region_id: 8)
# Country.create!(iso: "IT", name: "Italy", region_id: 8)
# Country.create!(iso: "JM", name: "Jamaica", region_id: 11)
# Country.create!(iso: "JO", name: "Jordan", region_id: 5)
# Country.create!(iso: "JP", name: "Japan", region_id: 3)
# Country.create!(iso: "KE", name: "Kenya", region_id: 2)
# Country.create!(iso: "KG", name: "Kyrgyzstan", region_id: 5)
# Country.create!(iso: "KH", name: "Cambodia", region_id: 6)
# Country.create!(iso: "KI", name: "Kiribati", region_id: 7)
# Country.create!(iso: "KM", name: "Comoros", region_id: 2)
# Country.create!(iso: "KN", name: "Saint Kitts and Nevis", region_id: 11)
# Country.create!(iso: "KP", name: "North Korea", region_id: 3)
# Country.create!(iso: "KR", name: "South Korea", region_id: 3)
# Country.create!(iso: "KW", name: "Kuwait", region_id: 5)
# Country.create!(iso: "KZ", name: "Kazakhstan", region_id: 5)
# Country.create!(iso: "LA", name: "Laos", region_id: 6)
# Country.create!(iso: "LB", name: "Lebanon", region_id: 5)
# Country.create!(iso: "LC", name: "Saint Lucia", region_id: 11)
# Country.create!(iso: "LI", name: "Liechtenstein", region_id: 8)
# Country.create!(iso: "LK", name: "Sri Lanka", region_id: 6)
# Country.create!(iso: "LR", name: "Liberia", region_id: 2)
# Country.create!(iso: "LS", name: "Lesotho", region_id: 2)
# Country.create!(iso: "LT", name: "Lithuania", region_id: 8)
# Country.create!(iso: "LU", name: "Luxembourg", region_id: 8)
# Country.create!(iso: "LV", name: "Latvia", region_id: 8)
# Country.create!(iso: "LY", name: "Libya", region_id: 1)
# Country.create!(iso: "MA", name: "Morocco", region_id: 1)
# Country.create!(iso: "MC", name: "Monaco", region_id: 8)
# Country.create!(iso: "MD", name: "Moldova", region_id: 4)
# Country.create!(iso: "ME", name: "Montenegro", region_id: 8)
# Country.create!(iso: "MG", name: "Madagascar", region_id: 2)
# Country.create!(iso: "MH", name: "Marshall Islands", region_id: 7)
# Country.create!(iso: "MK", name: "Macedonia", region_id: 8)
# Country.create!(iso: "ML", name: "Mali", region_id: 2)
# Country.create!(iso: "MM", name: "Myanmar", region_id: 6)
# Country.create!(iso: "MN", name: "Mongolia", region_id: 3)
# Country.create!(iso: "MO", name: "Macao", region_id: 3)
# Country.create!(iso: "MR", name: "Mauritania", region_id: 2)
# Country.create!(iso: "MT", name: "Malta", region_id: 8)
# Country.create!(iso: "MU", name: "Mauritius", region_id: 2)
# Country.create!(iso: "MV", name: "Maldives", region_id: 6)
# Country.create!(iso: "MW", name: "Malawi", region_id: 2)
# Country.create!(iso: "MX", name: "Mexico", region_id: 10)
# Country.create!(iso: "MY", name: "Malaysia", region_id: 6)
# Country.create!(iso: "MZ", name: "Mozambique", region_id: 2)
# Country.create!(iso: "NA", name: "Namibia", region_id: 2)
# Country.create!(iso: "NE", name: "Niger", region_id: 2)
# Country.create!(iso: "NG", name: "Nigeria", region_id: 2)
# Country.create!(iso: "NI", name: "Nicaragua", region_id: 10)
# Country.create!(iso: "NL", name: "Netherlands", region_id: 8)
# Country.create!(iso: "NO", name: "Norway", region_id: 8)
# Country.create!(iso: "NP", name: "Nepal", region_id: 6)
# Country.create!(iso: "NR", name: "Nauru", region_id: 7)
# Country.create!(iso: "NZ", name: "New Zealand", region_id: 7)
# Country.create!(iso: "OM", name: "Oman", region_id: 5)
# Country.create!(iso: "PA", name: "Panama", region_id: 10)
# Country.create!(iso: "PE", name: "Peru", region_id: 12)
# Country.create!(iso: "PG", name: "Papua New Guinea", region_id: 7)
# Country.create!(iso: "PH", name: "Philippines", region_id: 6)
# Country.create!(iso: "PK", name: "Pakistan", region_id: 5)
# Country.create!(iso: "PL", name: "Poland", region_id: 8)
# Country.create!(iso: "PS", name: "Palestinian Territories", region_id: 5)
# Country.create!(iso: "PT", name: "Portugal", region_id: 8)
# Country.create!(iso: "PW", name: "Palau", region_id: 7)
# Country.create!(iso: "PY", name: "Paraguay", region_id: 12)
# Country.create!(iso: "QA", name: "Qatar", region_id: 5)
# Country.create!(iso: "RO", name: "Romania", region_id: 8)
# Country.create!(iso: "RS", name: "Serbia", region_id: 8)
# Country.create!(iso: "RU", name: "Russia", region_id: 4)
# Country.create!(iso: "RW", name: "Rwanda", region_id: 2)
# Country.create!(iso: "SA", name: "Saudi Arabia", region_id: 5)
# Country.create!(iso: "SB", name: "Solomon Islands", region_id: 7)
# Country.create!(iso: "SC", name: "Seychelles", region_id: 2)
# Country.create!(iso: "SD", name: "Sudan", region_id: 2)
# Country.create!(iso: "SE", name: "Sweden", region_id: 8)
# Country.create!(iso: "SG", name: "Singapore", region_id: 6)
# Country.create!(iso: "SI", name: "Slovenia", region_id: 8)
# Country.create!(iso: "SK", name: "Slovakia", region_id: 8)
# Country.create!(iso: "SL", name: "Sierra Leone", region_id: 2)
# Country.create!(iso: "SM", name: "San Marino", region_id: 8)
# Country.create!(iso: "SN", name: "Senegal", region_id: 2)
# Country.create!(iso: "SO", name: "Somalia", region_id: 2)
# Country.create!(iso: "SR", name: "Suriname", region_id: 12)
# Country.create!(iso: "SS", name: "South Sudan", region_id: 2)
# Country.create!(iso: "ST", name: "Sao Tome and Principe", region_id: 2)
# Country.create!(iso: "SV", name: "El Salvador", region_id: 10)
# Country.create!(iso: "SX", name: "Sint Maarten", region_id: 11)
# Country.create!(iso: "SY", name: "Syria", region_id: 5)
# Country.create!(iso: "SZ", name: "Swaziland", region_id: 2)
# Country.create!(iso: "TD", name: "Chad", region_id: 2)
# Country.create!(iso: "TG", name: "Togo", region_id: 2)
# Country.create!(iso: "TH", name: "Thailand", region_id: 6)
# Country.create!(iso: "TJ", name: "Tajikistan", region_id: 5)
# Country.create!(iso: "TL", name: "Timor-Leste", region_id: 6)
# Country.create!(iso: "TM", name: "Turkmenistan", region_id: 5)
# Country.create!(iso: "TN", name: "Tunisia", region_id: 1)
# Country.create!(iso: "TO", name: "Tonga", region_id: 7)
# Country.create!(iso: "TR", name: "Turkey", region_id: 5)
# Country.create!(iso: "TT", name: "Trinidad and Tobago", region_id: 11)
# Country.create!(iso: "TV", name: "Tuvalu", region_id: 7)
# Country.create!(iso: "TZ", name: "Tanzania", region_id: 2)
# Country.create!(iso: "UA", name: "Ukraine", region_id: 4)
# Country.create!(iso: "UG", name: "Uganda", region_id: 2)
# Country.create!(iso: "US", name: "United States", region_id: 9)
# Country.create!(iso: "UY", name: "Uruguay", region_id: 12)
# Country.create!(iso: "UZ", name: "Uzbekistan", region_id: 5)
# Country.create!(iso: "VC", name: "Saint Vincent and the Grenadines", region_id: 11)
# Country.create!(iso: "VE", name: "Venezuela", region_id: 12)
# Country.create!(iso: "VN", name: "Vietnam", region_id: 6)
# Country.create!(iso: "VU", name: "Vanuatu", region_id: 7)
# Country.create!(iso: "WS", name: "Samoa", region_id: 7)
# Country.create!(iso: "YE", name: "Yemen", region_id: 5)
# Country.create!(iso: "ZA", name: "South Africa", region_id: 2)
# Country.create!(iso: "ZM", name: "Zambia", region_id: 2)
# Country.create!(iso: "ZW", name: "Zimbabwe", region_id: 2)

# # # Authors

# Author.delete_all

# # Afghanistan

# Author.create!(name: "Atiq Rahimi", country_id: 3, goodreads_id: 107055)
# Author.create!(name: "Khaled Hosseini", country_id: 3, goodreads_id: 569)

# # Australia
# Author.create!(name: "Peter Carey", country_id: 10, goodreads_id: 22595)
# Author.create!(name: "Kate Grenville", country_id: 10, goodreads_id: 132420)
# Author.create!(name: "Richard Flanagan", country_id: 10, goodreads_id: 8864)
# Author.create!(name: "Markus Zusak", country_id: 10, goodreads_id: 11466)
# Author.create!(name: "Craig Silvey", country_id: 10, goodreads_id: 341493)
# Author.create!(name: "Tim Winton", country_id: 10, goodreads_id: 19929)
# Author.create!(name: "Alexis Wright", country_id: 10, goodreads_id: 341920)
# Author.create!(name: "Kim Scott", country_id: 10, goodreads_id: 805409)
# Author.create!(name: "Steve Toltz", country_id: 10, goodreads_id: 837804)

# # New Zealand
# Author.create!(name: "Witi Ihimaera", country_id: 139, goodreads_id: 62911)
# Author.create!(name: "Keri Hulme", country_id: 139, goodreads_id: 7451)
# Author.create!(name: "Alan Duff", country_id: 139, goodreads_id: 22712)

# #Burundi
# Author.create!(name: "Sarah A. Al Shafei", country_id: 18, goodreads_id: 1127318)

# #Other authors

# Author.create!(name: "Ismail Kadare", country_id: 5, goodreads_id: 10838)

# Author.create!(name: "Yasmina Khadra", country_id: 50, goodreads_id: 71181)
# Author.create!(name: "Albert Salvadó", country_id: 1, goodreads_id: 5145598)
# Author.create!(name: "Jose Eduardo Agualusa", country_id: 7, goodreads_id: 484376)
# Author.create!(name: "Ondjaki", country_id: 7, goodreads_id: 884320)
# Author.create!(name: "Jamaica Kincaid", country_id: 4, goodreads_id: 39237)
# Author.create!(name: "Patricio Pron", country_id: 8, goodreads_id: 1239491)
# Author.create!(name: "Jorge Luis Borges", country_id: 8, goodreads_id: 500)
# Author.create!(name: "Julio Cortázar", country_id: 8, goodreads_id: 25824)
# Author.create!(name: "Elfriede Jelinek", country_id: 9, goodreads_id: 128607)
# Author.create!(name: "Joseph Roth", country_id: 9, goodreads_id: 30681)
# Author.create!(name: "Maksud Ibragimbekov", country_id: 11, goodreads_id: 5553607)
# Author.create!(name: "Chinghiz Gusseinov", country_id: 11, goodreads_id: 1290370)
# Author.create!(name: "Ian G. Strachan", country_id: 25, goodreads_id: 595981)
# Author.create!(name: "Ali Al Saeed", country_id: 18, goodreads_id: 87574)
# Author.create!(name: "Sarah A. Al Shafei", country_id: 18, goodreads_id: 2548086)
# Author.create!(name: "Tahmima Anam", country_id: 14, goodreads_id: 429519)
# Author.create!(name: "George Lamming", country_id: 13, goodreads_id: 163131)
# Author.create!(name: "Uladzimir Karatkevich", country_id: 28, goodreads_id: 12563712)
# Author.create!(name: "Stefan Hertmans", country_id: 15, goodreads_id: 824359)
# Author.create!(name: "Zoila Ellis", country_id: 29, goodreads_id: 559812)
# Author.create!(name: "Zee Edgell", country_id: 29, goodreads_id: 158277)
# Author.create!(name: "Olympe Bhêly-Quenum", country_id: 20, goodreads_id: 2039556)
# Author.create!(name: "Brian Burland", country_id: 21, goodreads_id: 411963)
# Author.create!(name: "Kunzang Choden", country_id: 26, goodreads_id: 131664)
# Author.create!(name: "Edmundo Paz Soldan", country_id: 23, goodreads_id: 2076101)
# Author.create!(name: "Juan de Recacoechea", country_id: 23, goodreads_id: 97251)
# Author.create!(name: "Ivo Andrić", country_id: 12, goodreads_id: 2147)
# Author.create!(name: "Meša Selimović", country_id: 12, goodreads_id: 205563)
# Author.create!(name: "Jorge Amado", country_id: 24, goodreads_id: 52683)
# Author.create!(name: "Clarice Lispector", country_id: 24, goodreads_id: 86098)
# Author.create!(name: "João Guimarães Rosa", country_id: 24, goodreads_id: 95937)
# Author.create!(name: "Ivan Vazov", country_id: 17, goodreads_id: 16877882)
# Author.create!(name: "Georgi Gospodinov", country_id: 17, goodreads_id: 325732)
# Author.create!(name: "Vaddey Ratner", country_id: 93, goodreads_id: 5332020)
# Author.create!(name: "Patrice Nganang", country_id: 37, goodreads_id: 4565657)
# Author.create!(name: "Mordecai Richler", country_id: 30, goodreads_id: 114539)
# Author.create!(name: "Joseph Boydon", country_id: 30, goodreads_id: 88550)
# Author.create!(name: "Margaret Atwood", country_id: 30, goodreads_id: 3472)
# Author.create!(name: "Wayne Johnston", country_id: 30, goodreads_id: 54816)
# Author.create!(name: "Alice Munro", country_id: 30, goodreads_id: 6410)
# Author.create!(name: "Joseph Brahim Seid", country_id: 175, goodreads_id: 1162250)
# Author.create!(name: "Roberto Bolano", country_id: 36, goodreads_id: 72039)
# Author.create!(name: "Isabelle Allende", country_id: 36, goodreads_id: 2238)
# Author.create!(name: "Jiang Rong", country_id: 38, goodreads_id: 590542)
# Author.create!(name: "Ha Jin", country_id: 38, goodreads_id: 8055)
# Author.create!(name: "Mo Yan", country_id: 38, goodreads_id: 121407)
# Author.create!(name: "Gao Xingjian", country_id: 38, goodreads_id: 25708)
# Author.create!(name: "Ma Jian", country_id: 38, goodreads_id: 53027)
# Author.create!(name: "Gabriel García Márquez", country_id: 39, goodreads_id: 13450)
# Author.create!(name: "José León Sánchez", country_id: 40, goodreads_id: 16261226)
# Author.create!(name: "Ahmadou Kourouma", country_id: 35, goodreads_id: 65220)
# Author.create!(name: "Bernard Binlin Dadié", country_id: 35, goodreads_id: 1108879)
# Author.create!(name: "Miroslav Krleža", country_id: 77, goodreads_id: 62421)
# Author.create!(name: "Guillermo Cabrera Infante", country_id: 41, goodreads_id: 49326)
# Author.create!(name: "José Lezama Lima", country_id: 41, goodreads_id: 119762)
# Author.create!(name: "Reinaldo Arenas", country_id: 41, goodreads_id: 12555)
# Author.create!(name: "Bohumil Hrabal", country_id: 44, goodreads_id: 50071)
# Author.create!(name: "Milan Kundera", country_id: 44, goodreads_id: 6343)
# Author.create!(name: "Franz Kafka", country_id: 44, goodreads_id: 5223)
# Author.create!(name: "Sony Labou Tansi", country_id: 31, goodreads_id: 379369)
# Author.create!(name: "Fiston Mwanza Mujila", country_id: 31, goodreads_id: 6132511)
# Author.create!(name: "Janne Teller", country_id: 47, goodreads_id: 453897)
# Author.create!(name: "Abdourahman Waberi", country_id: 46, goodreads_id: 56973)
# Author.create!(name: "Jean Rhys", country_id: 48, goodreads_id: 25022)
# Author.create!(name: "Junot Diaz", country_id: 49, goodreads_id: 55215)
# Author.create!(name: "Jorge Icaza", country_id: 51, goodreads_id: 66320)
# Author.create!(name: "Juan León Mera", country_id: 51, goodreads_id: 1041807)
# Author.create!(name: "Ahdaf Soueif", country_id: 53, goodreads_id: 51563)
# Author.create!(name: "Naguib Mahfouz", country_id: 53, goodreads_id: 5835922)
# Author.create!(name: "Horacio Castellanos Moya", country_id: 174, goodreads_id: 609209)
# Author.create!(name: "Manlio Argueta", country_id: 171, goodreads_id: 43595)
# Author.create!(name: "Juan Tomás Ávila Laurel", country_id: 70, goodreads_id: 7872921)

# Books

#Book.delete_all

# # Australia
# Book.create!(title: "The True History of the Kelly Gang", published_year: 2000, original_language: 'English', author_id: 3)

# Book.create!(title: "Oscar and Lucinda", published_year: 1998, original_language: 'English', author_id: 3)
# Book.create!(title: "Illywhacker", published_year: 1985, original_language: 'English', author_id: 3)

# Book.create!(title: "The Secret River", published_year: 2005, original_language: 'English', author_id: 4)

# Book.create!(title: "The Book Thief", published_year: 2005, original_language: 'English', author_id: 6)

# Book.create!(title: "Gould's Book of Fish", published_year: 2001, original_language: 'English', author_id: 5)

# Book.create!(title: "Jasper Jones", published_year: 2009, original_language: 'English', author_id: 7)

# Book.create!(title: "Cloudstreet", published_year: 1991, original_language: 'English', author_id: 8)

# Book.create!(title: "Carpentaria", published_year: 2006, original_language: 'English', author_id: 9)

# Book.create!(title: "Benang", published_year: 1999, original_language: 'English', author_id: 10)

# Book.create!(title: "A Fraction of the Whole", published_year: 2008, original_language: 'English', author_id: 11)

# # New Zealand

# Book.create!(title: "Once Were Warriors", published_year: 1990, original_language: 'English', author_id: 14)
# Book.create!(title: "Bone People", published_year: 1984, original_language: 'English', author_id: 13)
# Book.create!(title: "Whale Rider", published_year: 1987, original_language: 'English', author_id: 12)